[package]
name = "trexp"
version = "0.1.0"
edition = "2024"

[dependencies]
dirs-next = "2.0.0"
image = "0.25.8"
ratatui = "0.29.0"
ratatui-image = "8.0.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
